baseURL = "https://ahmed.sd/"
copyright = "Copyright © {year} Ahmed T. Ali. All rights reserved."
title = "Ahmed T. Ali"

defaultContentLanguage = "en"

theme = ["hugo-atom-feed", "hugo-bearblog"]

[permalinks]
blog = "blog/:year/:slug/"

[outputs]
section = ["HTML", "ATOM"]
