[build]
command = "hugo"
publish = "public"

[context.production.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.76.3"

[context.branch-deploy]
command = "hugo -b https://dev.ahmed.sd"

[context.branch-deploy.environment]
HUGO_VERSION = "0.76.3"

[[redirects]]
from = "https://z0al.netlify.com/*"
status = 301
to = "https://ahmed.sd/:splat"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
