[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.55"
HUGO_ENV = "production"

[context.branch-deploy]
command = "hugo -b https://dev.ahmed.sd"

[context.branch-deploy.environment]
HUGO_VERSION = "0.55"

[[redirects]]
  from = "https://z0al.netlify.com/*"
  to = "https://ahmed.sd/:splat"
  status = 301

[[headers]]
	for = "/*"
	[headers.values]
		Access-Control-Allow-Origin = "*"
